server:
  port: 9000

spring:
  h2:
    console:
      enabled: true
      path: /h2_console
  jpa:
    database-platform: H2
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: ALWAYS

